import { Inter } from "next/font/google";
import "./globals.css";
import AppContextProvider from "./Context/AppContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-slate-900 text-slate-200"}><AppContextProvider>{children}</AppContextProvider></body>
    </html>
  );
}
